/**
 * Generated by `npm run prerender:demo-audio` when narration MP3s are added to
 * the repository. Keep this file checked in with the matching files in
 * `public/assets/audio/`; an empty manifest is intentional for source-only
 * checkouts, where the player uses browser speech instead.
 */
export const demoAudioManifest = {
  version: 1,
  entries: {} as Record<string, string>,
} as const;

export function bundledDemoAudioFile(voice: string, line: string) {
  return demoAudioManifest.entries[`${voice}:${line.trim().replace(/\s+/g, " ")}`];
}
